{
    "timestamp": "2025-09-16T06:59:11.854911",
    "error_count": 0,
    "warning_count": 0,
    "info_count": 0,
    "failed_logins": 0,
    "top_messages": []
}{
    "timestamp": "2025-09-16T14:06:48.640775",
    "error_count": 0,
    "warning_count": 0,
    "info_count": 0,
    "failed_logins": 0,
    "top_messages": []
}
{
    "timestamp": "2025-09-16T14:07:58.891206",
    "error_count": 0,
    "warning_count": 0,
    "info_count": 0,
    "failed_logins": 0,
    "top_messages": []
}
{
    "timestamp": "2025-09-16T14:09:03.103759",
    "error_count": 0,
    "warning_count": 0,
    "info_count": 0,
    "failed_logins": 0,
    "top_messages": []
}
{
    "timestamp": "2025-09-16T14:10:25.822293",
    "error_count": 0,
    "warning_count": 0,
    "info_count": 0,
    "failed_logins": 0,
    "top_messages": []
}
{
    "timestamp": "2025-09-16T15:09:05.847539",
    "error_count": 0,
    "warning_count": 0,
    "info_count": 0,
    "failed_logins": 0,
    "top_messages": []
}
{
    "timestamp": "2025-09-16T15:26:33.018079",
    "error_count": 0,
    "warning_count": 0,
    "info_count": 1,
    "failed_logins": 0,
    "top_messages": []
}
{
    "timestamp": "2025-09-16T15:30:07.043103",
    "error_count": 1,
    "warning_count": 1,
    "info_count": 2,
    "failed_logins": 5,
    "top_messages": [
        "2025-09-16T15:29:08.272085+05:00 ZO sayed: This is a TEST ERROR message",
        "2025-09-16T15:29:17.871941+05:00 ZO sayed: This is a TEST WARNING message",
        "2025-09-16T15:27:48.881801+05:00 ZO su: pam_unix(su:auth): authentication failure; logname= uid=1000 euid=0 tty=/dev/pts/0 ruser=sayed rhost=  user=sayed",
        "2025-09-16T15:27:54.581374+05:00 ZO su: pam_unix(su:auth): authentication failure; logname= uid=1000 euid=0 tty=/dev/pts/0 ruser=sayed rhost=  user=sayed",
        "2025-09-16T15:28:07.562905+05:00 ZO su: pam_unix(su:auth): authentication failure; logname= uid=1000 euid=0 tty=/dev/pts/0 ruser=sayed rhost=  user=sayed"
    ]
}
{
    "timestamp": "2025-09-17 23:50:59",
    "error_count": 2,
    "warning_count": 1,
    "info_count": 2,
    "failed_logins": 5,
    "top_messages": [
        "2025-09-16T15:29:08.272085+05:00 ZO sayed: This is a TEST ERROR message",
        "2025-09-16T15:29:17.871941+05:00 ZO sayed: This is a TEST WARNING message",
        "2025-09-16T16:01:27.679021+05:00 ZO rsyslogd: file '/var/log/kern.log': open error: Permission denied [v8.2312.0 try https://www.rsyslog.com/e/2433 ]",
        "2025-09-16T15:27:48.881801+05:00 ZO su: pam_unix(su:auth): authentication failure; logname= uid=1000 euid=0 tty=/dev/pts/0 ruser=sayed rhost=  user=sayed",
        "2025-09-16T15:27:54.581374+05:00 ZO su: pam_unix(su:auth): authentication failure; logname= uid=1000 euid=0 tty=/dev/pts/0 ruser=sayed rhost=  user=sayed"
    ]
}
{
    "timestamp": "2025-09-18 00:59:31",
    "error_count": 2,
    "warning_count": 1,
    "info_count": 2,
    "failed_logins": 5,
    "top_messages": [
        "2025-09-16T15:29:08.272085+05:00 ZO sayed: This is a TEST ERROR message",
        "2025-09-16T15:29:17.871941+05:00 ZO sayed: This is a TEST WARNING message",
        "2025-09-16T16:01:27.679021+05:00 ZO rsyslogd: file '/var/log/kern.log': open error: Permission denied [v8.2312.0 try https://www.rsyslog.com/e/2433 ]",
        "2025-09-16T15:27:48.881801+05:00 ZO su: pam_unix(su:auth): authentication failure; logname= uid=1000 euid=0 tty=/dev/pts/0 ruser=sayed rhost=  user=sayed",
        "2025-09-16T15:27:54.581374+05:00 ZO su: pam_unix(su:auth): authentication failure; logname= uid=1000 euid=0 tty=/dev/pts/0 ruser=sayed rhost=  user=sayed"
    ]
}
{
    "timestamp": "2025-09-19 01:55:28",
    "error_count": 12,
    "warning_count": 2,
    "info_count": 948,
    "failed_logins": 0,
    "top_messages": [
        "2025-09-12 00:22:48,771 [ERROR] \u274c Git commit/push failed: Command '['git', 'commit', '-m', 'Update system report 2025-09-12 00:22:48']' returned non-zero exit status 1.",
        "2025-09-12 00:45:04,549 [ERROR] \u274c Git commit/push failed: Command '['git', 'push']' returned non-zero exit status 1.",
        "2025-09-12 00:50:03,793 [ERROR] \u274c Git commit/push failed: Command '['git', 'push']' returned non-zero exit status 1.",
        "2025-09-12 00:55:03,997 [ERROR] \u274c Git commit/push failed: Command '['git', 'push']' returned non-zero exit status 1.",
        "2025-09-12 01:01:37,261 [ERROR] \u274c Git command failed: Command '['git', 'pull', '--rebase', 'origin', 'main']' returned non-zero exit status 128."
    ]
}
{
    "timestamp": "2025-09-19 01:57:47",
    "error_count": 13,
    "warning_count": 3,
    "info_count": 949,
    "failed_logins": 1,
    "top_messages": [
        "2025-09-12 00:22:48,771 [ERROR] \u274c Git commit/push failed: Command '['git', 'commit', '-m', 'Update system report 2025-09-12 00:22:48']' returned non-zero exit status 1.",
        "2025-09-12 00:45:04,549 [ERROR] \u274c Git commit/push failed: Command '['git', 'push']' returned non-zero exit status 1.",
        "2025-09-12 00:50:03,793 [ERROR] \u274c Git commit/push failed: Command '['git', 'push']' returned non-zero exit status 1.",
        "2025-09-12 00:55:03,997 [ERROR] \u274c Git commit/push failed: Command '['git', 'push']' returned non-zero exit status 1.",
        "2025-09-12 01:01:37,261 [ERROR] \u274c Git command failed: Command '['git', 'pull', '--rebase', 'origin', 'main']' returned non-zero exit status 128."
    ]
}
{
    "timestamp": "2025-09-19 02:00:01",
    "error_count": 13,
    "warning_count": 3,
    "info_count": 949,
    "failed_logins": 1,
    "top_messages": [
        "2025-09-12 00:22:48,771 [ERROR] \u274c Git commit/push failed: Command '['git', 'commit', '-m', 'Update system report 2025-09-12 00:22:48']' returned non-zero exit status 1.",
        "2025-09-12 00:45:04,549 [ERROR] \u274c Git commit/push failed: Command '['git', 'push']' returned non-zero exit status 1.",
        "2025-09-12 00:50:03,793 [ERROR] \u274c Git commit/push failed: Command '['git', 'push']' returned non-zero exit status 1.",
        "2025-09-12 00:55:03,997 [ERROR] \u274c Git commit/push failed: Command '['git', 'push']' returned non-zero exit status 1.",
        "2025-09-12 01:01:37,261 [ERROR] \u274c Git command failed: Command '['git', 'pull', '--rebase', 'origin', 'main']' returned non-zero exit status 128."
    ]
}
{
    "timestamp": "2025-09-19 02:07:01",
    "error_count": 13,
    "warning_count": 3,
    "info_count": 951,
    "failed_logins": 1,
    "top_messages": [
        "2025-09-12 00:22:48,771 [ERROR] \u274c Git commit/push failed: Command '['git', 'commit', '-m', 'Update system report 2025-09-12 00:22:48']' returned non-zero exit status 1.",
        "2025-09-12 00:45:04,549 [ERROR] \u274c Git commit/push failed: Command '['git', 'push']' returned non-zero exit status 1.",
        "2025-09-12 00:50:03,793 [ERROR] \u274c Git commit/push failed: Command '['git', 'push']' returned non-zero exit status 1.",
        "2025-09-12 00:55:03,997 [ERROR] \u274c Git commit/push failed: Command '['git', 'push']' returned non-zero exit status 1.",
        "2025-09-12 01:01:37,261 [ERROR] \u274c Git command failed: Command '['git', 'pull', '--rebase', 'origin', 'main']' returned non-zero exit status 128."
    ]
}
